name: Deploy server

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment By ahay.my.id
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          port: 22
          command_timeout: 200m
          script: |
            cd ~
            ./deploy.sh
